// 514 Kabupaten/Kota di Indonesia — per Juli 2026 (38 provinsi)
// Sumber: Permendagri No. 58 Tahun 2021 + update DOB Papua

export const cities = [
  // ── ACEH ──
  { slug: "banda-aceh", name: "Banda Aceh" },
  { slug: "sabang", name: "Sabang" },
  { slug: "lhokseumawe", name: "Lhokseumawe" },
  { slug: "langsa", name: "Langsa" },
  { slug: "subulussalam", name: "Subulussalam" },
  { slug: "aceh-besar", name: "Aceh Besar" },
  { slug: "aceh-barat", name: "Aceh Barat" },
  { slug: "aceh-barat-daya", name: "Aceh Barat Daya" },
  { slug: "aceh-jaya", name: "Aceh Jaya" },
  { slug: "aceh-selatan", name: "Aceh Selatan" },
  { slug: "aceh-singkil", name: "Aceh Singkil" },
  { slug: "aceh-tamiang", name: "Aceh Tamiang" },
  { slug: "aceh-tengah", name: "Aceh Tengah" },
  { slug: "aceh-tenggara", name: "Aceh Tenggara" },
  { slug: "aceh-timur", name: "Aceh Timur" },
  { slug: "aceh-utara", name: "Aceh Utara" },
  { slug: "bener-meriah", name: "Bener Meriah" },
  { slug: "bireuen", name: "Bireuen" },
  { slug: "gayo-lues", name: "Gayo Lues" },
  { slug: "nagan-raya", name: "Nagan Raya" },
  { slug: "pidie", name: "Pidie" },
  { slug: "pidie-jaya", name: "Pidie Jaya" },
  { slug: "simeulue", name: "Simeulue" },

  // ── SUMATERA UTARA ──
  { slug: "medan", name: "Medan" },
  { slug: "binjai", name: "Binjai" },
  { slug: "gunungsitoli", name: "Gunungsitoli" },
  { slug: "padang-sidempuan", name: "Padang Sidempuan" },
  { slug: "pematangsiantar", name: "Pematangsiantar" },
  { slug: "sibolga", name: "Sibolga" },
  { slug: "tanjungbalai", name: "Tanjungbalai" },
  { slug: "tebing-tinggi", name: "Tebing Tinggi" },
  { slug: "asahan", name: "Asahan" },
  { slug: "batubara", name: "Batubara" },
  { slug: "dairi", name: "Dairi" },
  { slug: "deli-serdang", name: "Deli Serdang" },
  { slug: "humbang-hasundutan", name: "Humbang Hasundutan" },
  { slug: "karo", name: "Karo" },
  { slug: "labuhanbatu", name: "Labuhanbatu" },
  { slug: "labuhanbatu-selatan", name: "Labuhanbatu Selatan" },
  { slug: "labuhanbatu-utara", name: "Labuhanbatu Utara" },
  { slug: "langkat", name: "Langkat" },
  { slug: "mandailing-natal", name: "Mandailing Natal" },
  { slug: "nias", name: "Nias" },
  { slug: "nias-barat", name: "Nias Barat" },
  { slug: "nias-selatan", name: "Nias Selatan" },
  { slug: "nias-utara", name: "Nias Utara" },
  { slug: "padang-lawas", name: "Padang Lawas" },
  { slug: "padang-lawas-utara", name: "Padang Lawas Utara" },
  { slug: "pakpak-bharat", name: "Pakpak Bharat" },
  { slug: "samosir", name: "Samosir" },
  { slug: "serdang-bedagai", name: "Serdang Bedagai" },
  { slug: "simalungun", name: "Simalungun" },
  { slug: "tapanuli-selatan", name: "Tapanuli Selatan" },
  { slug: "tapanuli-tengah", name: "Tapanuli Tengah" },
  { slug: "tapanuli-utara", name: "Tapanuli Utara" },
  { slug: "toba", name: "Toba" },

  // ── SUMATERA BARAT ──
  { slug: "padang", name: "Padang" },
  { slug: "bukittinggi", name: "Bukittinggi" },
  { slug: "padang-panjang", name: "Padang Panjang" },
  { slug: "pariaman", name: "Pariaman" },
  { slug: "payakumbuh", name: "Payakumbuh" },
  { slug: "sawahlunto", name: "Sawahlunto" },
  { slug: "solok", name: "Solok" },
  { slug: "agam", name: "Agam" },
  { slug: "dharmasraya", name: "Dharmasraya" },
  { slug: "kepulauan-mentawai", name: "Kepulauan Mentawai" },
  { slug: "lima-puluh-kota", name: "Lima Puluh Kota" },
  { slug: "padang-pariaman", name: "Padang Pariaman" },
  { slug: "pasaman", name: "Pasaman" },
  { slug: "pasaman-barat", name: "Pasaman Barat" },
  { slug: "pesisir-selatan", name: "Pesisir Selatan" },
  { slug: "sijunjung", name: "Sijunjung" },
  { slug: "solok-selatan", name: "Solok Selatan" },
  { slug: "tanah-datar", name: "Tanah Datar" },

  // ── RIAU ──
  { slug: "pekanbaru", name: "Pekanbaru" },
  { slug: "dumai", name: "Dumai" },
  { slug: "bengkalis", name: "Bengkalis" },
  { slug: "indragiri-hilir", name: "Indragiri Hilir" },
  { slug: "indragiri-hulu", name: "Indragiri Hulu" },
  { slug: "kampar", name: "Kampar" },
  { slug: "kepulauan-meranti", name: "Kepulauan Meranti" },
  { slug: "kuantan-singingi", name: "Kuantan Singingi" },
  { slug: "pelalawan", name: "Pelalawan" },
  { slug: "rokan-hilir", name: "Rokan Hilir" },
  { slug: "rokan-hulu", name: "Rokan Hulu" },
  { slug: "siak", name: "Siak" },

  // ── KEPULAUAN RIAU ──
  { slug: "batam", name: "Batam" },
  { slug: "tanjung-pinang", name: "Tanjung Pinang" },
  { slug: "bintan", name: "Bintan" },
  { slug: "karimun", name: "Karimun" },
  { slug: "kepulauan-anambas", name: "Kepulauan Anambas" },
  { slug: "lingga", name: "Lingga" },
  { slug: "natuna", name: "Natuna" },

  // ── JAMBI ──
  { slug: "jambi", name: "Jambi" },
  { slug: "sungai-penuh", name: "Sungai Penuh" },
  { slug: "batanghari", name: "Batanghari" },
  { slug: "bungo", name: "Bungo" },
  { slug: "kerinci", name: "Kerinci" },
  { slug: "merangin", name: "Merangin" },
  { slug: "muaro-jambi", name: "Muaro Jambi" },
  { slug: "sarolangun", name: "Sarolangun" },
  { slug: "tanjung-jabung-barat", name: "Tanjung Jabung Barat" },
  { slug: "tanjung-jabung-timur", name: "Tanjung Jabung Timur" },
  { slug: "tebo", name: "Tebo" },

  // ── SUMATERA SELATAN ──
  { slug: "palembang", name: "Palembang" },
  { slug: "lubuklinggau", name: "Lubuklinggau" },
  { slug: "pagar-alam", name: "Pagar Alam" },
  { slug: "prabumulih", name: "Prabumulih" },
  { slug: "banyuasin", name: "Banyuasin" },
  { slug: "empat-lawang", name: "Empat Lawang" },
  { slug: "lahat", name: "Lahat" },
  { slug: "muara-enim", name: "Muara Enim" },
  { slug: "musi-banyuasin", name: "Musi Banyuasin" },
  { slug: "musi-rawas", name: "Musi Rawas" },
  { slug: "musi-rawas-utara", name: "Musi Rawas Utara" },
  { slug: "ogan-ilir", name: "Ogan Ilir" },
  { slug: "ogan-komering-ilir", name: "Ogan Komering Ilir" },
  { slug: "ogan-komering-ulu", name: "Ogan Komering Ulu" },
  { slug: "ogan-komering-ulu-selatan", name: "Ogan Komering Ulu Selatan" },
  { slug: "ogan-komering-ulu-timur", name: "Ogan Komering Ulu Timur" },
  { slug: "penukal-abab-lematang-ilir", name: "Penukal Abab Lematang Ilir" },

  // ── BANGKA BELITUNG ──
  { slug: "pangkalpinang", name: "Pangkalpinang" },
  { slug: "bangka", name: "Bangka" },
  { slug: "bangka-barat", name: "Bangka Barat" },
  { slug: "bangka-selatan", name: "Bangka Selatan" },
  { slug: "bangka-tengah", name: "Bangka Tengah" },
  { slug: "belitung", name: "Belitung" },
  { slug: "belitung-timur", name: "Belitung Timur" },

  // ── BENGKULU ──
  { slug: "bengkulu", name: "Bengkulu" },
  { slug: "bengkulu-selatan", name: "Bengkulu Selatan" },
  { slug: "bengkulu-tengah", name: "Bengkulu Tengah" },
  { slug: "bengkulu-utara", name: "Bengkulu Utara" },
  { slug: "kaur", name: "Kaur" },
  { slug: "kepahiang", name: "Kepahiang" },
  { slug: "lebong", name: "Lebong" },
  { slug: "mukomuko", name: "Mukomuko" },
  { slug: "rejang-lebong", name: "Rejang Lebong" },
  { slug: "seluma", name: "Seluma" },

  // ── LAMPUNG ──
  { slug: "bandar-lampung", name: "Bandar Lampung" },
  { slug: "metro", name: "Metro" },
  { slug: "lampung-barat", name: "Lampung Barat" },
  { slug: "lampung-selatan", name: "Lampung Selatan" },
  { slug: "lampung-tengah", name: "Lampung Tengah" },
  { slug: "lampung-timur", name: "Lampung Timur" },
  { slug: "lampung-utara", name: "Lampung Utara" },
  { slug: "mesuji", name: "Mesuji" },
  { slug: "pesawaran", name: "Pesawaran" },
  { slug: "pesisir-barat", name: "Pesisir Barat" },
  { slug: "pringsewu", name: "Pringsewu" },
  { slug: "tanggamus", name: "Tanggamus" },
  { slug: "tulang-bawang", name: "Tulang Bawang" },
  { slug: "tulang-bawang-barat", name: "Tulang Bawang Barat" },
  { slug: "way-kanan", name: "Way Kanan" },

  // ── DKI JAKARTA ──
  { slug: "jakarta-pusat", name: "Jakarta Pusat" },
  { slug: "jakarta-utara", name: "Jakarta Utara" },
  { slug: "jakarta-barat", name: "Jakarta Barat" },
  { slug: "jakarta-selatan", name: "Jakarta Selatan" },
  { slug: "jakarta-timur", name: "Jakarta Timur" },
  { slug: "kepulauan-seribu", name: "Kepulauan Seribu" },

  // ── JAWA BARAT ──
  { slug: "bandung", name: "Bandung" },
  { slug: "banjar", name: "Banjar" },
  { slug: "bekasi", name: "Bekasi" },
  { slug: "bogor", name: "Bogor" },
  { slug: "cimahi", name: "Cimahi" },
  { slug: "cirebon", name: "Cirebon" },
  { slug: "depok", name: "Depok" },
  { slug: "sukabumi", name: "Sukabumi" },
  { slug: "tasikmalaya", name: "Tasikmalaya" },
  { slug: "bandung-barat", name: "Bandung Barat" },
  { slug: "bekasi-kota", name: "Bekasi" },
  { slug: "bogor-kota", name: "Bogor" },
  { slug: "ciamis", name: "Ciamis" },
  { slug: "cianjur", name: "Cianjur" },
  { slug: "cirebon-kota", name: "Cirebon" },
  { slug: "garut", name: "Garut" },
  { slug: "indramayu", name: "Indramayu" },
  { slug: "karawang", name: "Karawang" },
  { slug: "kuningan", name: "Kuningan" },
  { slug: "majalengka", name: "Majalengka" },
  { slug: "pangandaran", name: "Pangandaran" },
  { slug: "purwakarta", name: "Purwakarta" },
  { slug: "subang", name: "Subang" },
  { slug: "sukabumi-kota", name: "Sukabumi" },
  { slug: "sumedang", name: "Sumedang" },
  { slug: "tasikmalaya-kota", name: "Tasikmalaya" },

  // ── BANTEN ──
  { slug: "cilegon", name: "Cilegon" },
  { slug: "serang", name: "Serang" },
  { slug: "tangerang", name: "Tangerang" },
  { slug: "tangerang-selatan", name: "Tangerang Selatan" },
  { slug: "lebak", name: "Lebak" },
  { slug: "pandeglang", name: "Pandeglang" },
  { slug: "serang-kota", name: "Serang" },
  { slug: "tangerang-kota", name: "Tangerang" },

  // ── JAWA TENGAH ──
  { slug: "magelang", name: "Magelang" },
  { slug: "pekalongan", name: "Pekalongan" },
  { slug: "salatiga", name: "Salatiga" },
  { slug: "semarang", name: "Semarang" },
  { slug: "surakarta", name: "Surakarta (Solo)" },
  { slug: "tegal", name: "Tegal" },
  { slug: "banjarnegara", name: "Banjarnegara" },
  { slug: "banyumas", name: "Banyumas" },
  { slug: "batang", name: "Batang" },
  { slug: "blora", name: "Blora" },
  { slug: "boyolali", name: "Boyolali" },
  { slug: "brebes", name: "Brebes" },
  { slug: "cilacap", name: "Cilacap" },
  { slug: "demak", name: "Demak" },
  { slug: "grobogan", name: "Grobogan" },
  { slug: "jepara", name: "Jepara" },
  { slug: "karanganyar", name: "Karanganyar" },
  { slug: "kebumen", name: "Kebumen" },
  { slug: "kendal", name: "Kendal" },
  { slug: "klaten", name: "Klaten" },
  { slug: "kudus", name: "Kudus" },
  { slug: "magelang-kota", name: "Magelang" },
  { slug: "pati", name: "Pati" },
  { slug: "pekalongan-kota", name: "Pekalongan" },
  { slug: "pemalang", name: "Pemalang" },
  { slug: "purbalingga", name: "Purbalingga" },
  { slug: "purworejo", name: "Purworejo" },
  { slug: "rembang", name: "Rembang" },
  { slug: "semarang-kota", name: "Semarang" },
  { slug: "sragen", name: "Sragen" },
  { slug: "sukoharjo", name: "Sukoharjo" },
  { slug: "tegal-kota", name: "Tegal" },
  { slug: "temanggung", name: "Temanggung" },
  { slug: "wonogiri", name: "Wonogiri" },
  { slug: "wonosobo", name: "Wonosobo" },

  // ── DI YOGYAKARTA ──
  { slug: "yogyakarta", name: "Yogyakarta" },
  { slug: "bantul", name: "Bantul" },
  { slug: "gunungkidul", name: "Gunungkidul" },
  { slug: "kulon-progo", name: "Kulon Progo" },
  { slug: "sleman", name: "Sleman" },

  // ── JAWA TIMUR ──
  { slug: "surabaya", name: "Surabaya" },
  { slug: "batu", name: "Batu" },
  { slug: "blitar", name: "Blitar" },
  { slug: "kediri", name: "Kediri" },
  { slug: "madiun", name: "Madiun" },
  { slug: "malang", name: "Malang" },
  { slug: "mojokerto", name: "Mojokerto" },
  { slug: "pasuruan", name: "Pasuruan" },
  { slug: "probolinggo", name: "Probolinggo" },
  { slug: "bangkalan", name: "Bangkalan" },
  { slug: "banyuwangi", name: "Banyuwangi" },
  { slug: "blitar-kota", name: "Blitar" },
  { slug: "bojonegoro", name: "Bojonegoro" },
  { slug: "bondowoso", name: "Bondowoso" },
  { slug: "gresik", name: "Gresik" },
  { slug: "jember", name: "Jember" },
  { slug: "jombang", name: "Jombang" },
  { slug: "kediri-kota", name: "Kediri" },
  { slug: "lamongan", name: "Lamongan" },
  { slug: "lumajang", name: "Lumajang" },
  { slug: "madiun-kota", name: "Madiun" },
  { slug: "magetan", name: "Magetan" },
  { slug: "malang-kota", name: "Malang" },
  { slug: "mojokerto-kota", name: "Mojokerto" },
  { slug: "nganjuk", name: "Nganjuk" },
  { slug: "ngawi", name: "Ngawi" },
  { slug: "pacitan", name: "Pacitan" },
  { slug: "pamekasan", name: "Pamekasan" },
  { slug: "pasuruan-kota", name: "Pasuruan" },
  { slug: "ponorogo", name: "Ponorogo" },
  { slug: "probolinggo-kota", name: "Probolinggo" },
  { slug: "sampang", name: "Sampang" },
  { slug: "sidoarjo", name: "Sidoarjo" },
  { slug: "situbondo", name: "Situbondo" },
  { slug: "sumenep", name: "Sumenep" },
  { slug: "trenggalek", name: "Trenggalek" },
  { slug: "tuban", name: "Tuban" },
  { slug: "tulungagung", name: "Tulungagung" },

  // ── BALI ──
  { slug: "denpasar", name: "Denpasar" },
  { slug: "badung", name: "Badung" },
  { slug: "bangli", name: "Bangli" },
  { slug: "buleleng", name: "Buleleng" },
  { slug: "gianyar", name: "Gianyar" },
  { slug: "jembrana", name: "Jembrana" },
  { slug: "karangasem", name: "Karangasem" },
  { slug: "klungkung", name: "Klungkung" },
  { slug: "tabanan", name: "Tabanan" },

  // ── NUSA TENGGARA BARAT ──
  { slug: "mataram", name: "Mataram" },
  { slug: "bima", name: "Bima" },
  { slug: "bima-kota", name: "Bima" },
  { slug: "dompu", name: "Dompu" },
  { slug: "lombok-barat", name: "Lombok Barat" },
  { slug: "lombok-tengah", name: "Lombok Tengah" },
  { slug: "lombok-timur", name: "Lombok Timur" },
  { slug: "lombok-utara", name: "Lombok Utara" },
  { slug: "sumbawa", name: "Sumbawa" },
  { slug: "sumbawa-barat", name: "Sumbawa Barat" },

  // ── NUSA TENGGARA TIMUR ──
  { slug: "kupang", name: "Kupang" },
  { slug: "kupang-kota", name: "Kupang" },
  { slug: "alor", name: "Alor" },
  { slug: "belu", name: "Belu" },
  { slug: "ende", name: "Ende" },
  { slug: "flores-timur", name: "Flores Timur" },
  { slug: "kupang-kab", name: "Kupang" },
  { slug: "lembata", name: "Lembata" },
  { slug: "malaka", name: "Malaka" },
  { slug: "manggarai", name: "Manggarai" },
  { slug: "manggarai-barat", name: "Manggarai Barat" },
  { slug: "manggarai-timur", name: "Manggarai Timur" },
  { slug: "nagekeo", name: "Nagekeo" },
  { slug: "ngada", name: "Ngada" },
  { slug: "rote-ndao", name: "Rote Ndao" },
  { slug: "sabu-raijua", name: "Sabu Raijua" },
  { slug: "sikka", name: "Sikka" },
  { slug: "sumba-barat", name: "Sumba Barat" },
  { slug: "sumba-barat-daya", name: "Sumba Barat Daya" },
  { slug: "sumba-tengah", name: "Sumba Tengah" },
  { slug: "sumba-timur", name: "Sumba Timur" },
  { slug: "timor-tengah-selatan", name: "Timor Tengah Selatan" },
  { slug: "timor-tengah-utara", name: "Timor Tengah Utara" },

  // ── KALIMANTAN BARAT ──
  { slug: "pontianak", name: "Pontianak" },
  { slug: "singkawang", name: "Singkawang" },
  { slug: "bengkayang", name: "Bengkayang" },
  { slug: "kapuas-hulu", name: "Kapuas Hulu" },
  { slug: "kayong-utara", name: "Kayong Utara" },
  { slug: "ketapang", name: "Ketapang" },
  { slug: "kubu-raya", name: "Kubu Raya" },
  { slug: "landak", name: "Landak" },
  { slug: "melawi", name: "Melawi" },
  { slug: "mempawah", name: "Mempawah" },
  { slug: "sambas", name: "Sambas" },
  { slug: "sanggau", name: "Sanggau" },
  { slug: "sekadau", name: "Sekadau" },
  { slug: "sintang", name: "Sintang" },

  // ── KALIMANTAN TENGAH ──
  { slug: "palangkaraya", name: "Palangkaraya" },
  { slug: "barito-selatan", name: "Barito Selatan" },
  { slug: "barito-timur", name: "Barito Timur" },
  { slug: "barito-utara", name: "Barito Utara" },
  { slug: "gunung-mas", name: "Gunung Mas" },
  { slug: "kapuas", name: "Kapuas" },
  { slug: "katingan", name: "Katingan" },
  { slug: "kotawaringin-barat", name: "Kotawaringin Barat" },
  { slug: "kotawaringin-timur", name: "Kotawaringin Timur" },
  { slug: "lamandau", name: "Lamandau" },
  { slug: "murung-raya", name: "Murung Raya" },
  { slug: "pulang-pisau", name: "Pulang Pisau" },
  { slug: "seruyan", name: "Seruyan" },
  { slug: "sukamara", name: "Sukamara" },

  // ── KALIMANTAN SELATAN ──
  { slug: "banjarmasin", name: "Banjarmasin" },
  { slug: "banjarbaru", name: "Banjarbaru" },
  { slug: "balangan", name: "Balangan" },
  { slug: "banjar", name: "Banjar" },
  { slug: "barito-kuala", name: "Barito Kuala" },
  { slug: "hulu-sungai-selatan", name: "Hulu Sungai Selatan" },
  { slug: "hulu-sungai-tengah", name: "Hulu Sungai Tengah" },
  { slug: "hulu-sungai-utara", name: "Hulu Sungai Utara" },
  { slug: "kotabaru", name: "Kotabaru" },
  { slug: "tabalong", name: "Tabalong" },
  { slug: "tanah-bumbu", name: "Tanah Bumbu" },
  { slug: "tanah-laut", name: "Tanah Laut" },
  { slug: "tapin", name: "Tapin" },

  // ── KALIMANTAN TIMUR ──
  { slug: "samarinda", name: "Samarinda" },
  { slug: "balikpapan", name: "Balikpapan" },
  { slug: "bontang", name: "Bontang" },
  { slug: "berau", name: "Berau" },
  { slug: "kutai-barat", name: "Kutai Barat" },
  { slug: "kutai-kartanegara", name: "Kutai Kartanegara" },
  { slug: "kutai-timur", name: "Kutai Timur" },
  { slug: "mahakam-ulu", name: "Mahakam Ulu" },
  { slug: "paser", name: "Paser" },
  { slug: "penajam-paser-utara", name: "Penajam Paser Utara" },
  { slug: "samarinda-kota", name: "Samarinda" },

  // ── KALIMANTAN UTARA ──
  { slug: "tarakan", name: "Tarakan" },
  { slug: "bulungan", name: "Bulungan" },
  { slug: "malinau", name: "Malinau" },
  { slug: "nunukan", name: "Nunukan" },
  { slug: "tana-tidung", name: "Tana Tidung" },

  // ── SULAWESI UTARA ──
  { slug: "manado", name: "Manado" },
  { slug: "bitung", name: "Bitung" },
  { slug: "kotamobagu", name: "Kotamobagu" },
  { slug: "tomohon", name: "Tomohon" },
  { slug: "bolaang-mongondow", name: "Bolaang Mongondow" },
  { slug: "bolaang-mongondow-selatan", name: "Bolaang Mongondow Selatan" },
  { slug: "bolaang-mongondow-timur", name: "Bolaang Mongondow Timur" },
  { slug: "bolaang-mongondow-utara", name: "Bolaang Mongondow Utara" },
  { slug: "kepulauan-sangihe", name: "Kepulauan Sangihe" },
  { slug: "kepulauan-siau-tagulandang-biaro", name: "Kepulauan Siau Tagulandang Biaro" },
  { slug: "kepulauan-talaud", name: "Kepulauan Talaud" },
  { slug: "minahasa", name: "Minahasa" },
  { slug: "minahasa-selatan", name: "Minahasa Selatan" },
  { slug: "minahasa-tenggara", name: "Minahasa Tenggara" },
  { slug: "minahasa-utara", name: "Minahasa Utara" },

  // ── SULAWESI TENGAH ──
  { slug: "palu", name: "Palu" },
  { slug: "banggai", name: "Banggai" },
  { slug: "banggai-kepulauan", name: "Banggai Kepulauan" },
  { slug: "banggai-laut", name: "Banggai Laut" },
  { slug: "buol", name: "Buol" },
  { slug: "donggala", name: "Donggala" },
  { slug: "morowali", name: "Morowali" },
  { slug: "morowali-utara", name: "Morowali Utara" },
  { slug: "parigi-moutong", name: "Parigi Moutong" },
  { slug: "poso", name: "Poso" },
  { slug: "sigi", name: "Sigi" },
  { slug: "tojo-una-una", name: "Tojo Una-Una" },
  { slug: "tolitoli", name: "Tolitoli" },

  // ── SULAWESI SELATAN ──
  { slug: "makassar", name: "Makassar" },
  { slug: "palopo", name: "Palopo" },
  { slug: "parepare", name: "Parepare" },
  { slug: "bantaeng", name: "Bantaeng" },
  { slug: "barru", name: "Barru" },
  { slug: "bone", name: "Bone" },
  { slug: "bulukumba", name: "Bulukumba" },
  { slug: "enrekang", name: "Enrekang" },
  { slug: "gowa", name: "Gowa" },
  { slug: "jeneponto", name: "Jeneponto" },
  { slug: "kepulauan-selayar", name: "Kepulauan Selayar" },
  { slug: "luwu", name: "Luwu" },
  { slug: "luwu-timur", name: "Luwu Timur" },
  { slug: "luwu-utara", name: "Luwu Utara" },
  { slug: "maros", name: "Maros" },
  { slug: "pangkajene-kepulauan", name: "Pangkajene Kepulauan" },
  { slug: "pinrang", name: "Pinrang" },
  { slug: "sidenreng-rappang", name: "Sidenreng Rappang" },
  { slug: "sinjai", name: "Sinjai" },
  { slug: "soppeng", name: "Soppeng" },
  { slug: "takalar", name: "Takalar" },
  { slug: "tana-toraja", name: "Tana Toraja" },
  { slug: "toraja-utara", name: "Toraja Utara" },
  { slug: "wajo", name: "Wajo" },

  // ── SULAWESI TENGGARA ──
  { slug: "kendari", name: "Kendari" },
  { slug: "bau-bau", name: "Bau-Bau" },
  { slug: "bombana", name: "Bombana" },
  { slug: "buton", name: "Buton" },
  { slug: "buton-selatan", name: "Buton Selatan" },
  { slug: "buton-tengah", name: "Buton Tengah" },
  { slug: "buton-utara", name: "Buton Utara" },
  { slug: "kolaka", name: "Kolaka" },
  { slug: "kolaka-timur", name: "Kolaka Timur" },
  { slug: "kolaka-utara", name: "Kolaka Utara" },
  { slug: "konawe", name: "Konawe" },
  { slug: "konawe-kepulauan", name: "Konawe Kepulauan" },
  { slug: "konawe-selatan", name: "Konawe Selatan" },
  { slug: "konawe-utara", name: "Konawe Utara" },
  { slug: "muna", name: "Muna" },
  { slug: "muna-barat", name: "Muna Barat" },
  { slug: "wakatobi", name: "Wakatobi" },

  // ── GORONTALO ──
  { slug: "gorontalo", name: "Gorontalo" },
  { slug: "gorontalo-kota", name: "Gorontalo" },
  { slug: "boalemo", name: "Boalemo" },
  { slug: "bone-bolango", name: "Bone Bolango" },
  { slug: "gorontalo-utara", name: "Gorontalo Utara" },
  { slug: "pohuwato", name: "Pohuwato" },

  // ── SULAWESI BARAT ──
  { slug: "mamuju", name: "Mamuju" },
  { slug: "majene", name: "Majene" },
  { slug: "mamasa", name: "Mamasa" },
  { slug: "mamuju-tengah", name: "Mamuju Tengah" },
  { slug: "pasangkayu", name: "Pasangkayu" },
  { slug: "polewali-mandar", name: "Polewali Mandar" },

  // ── MALUKU ──
  { slug: "ambon", name: "Ambon" },
  { slug: "tual", name: "Tual" },
  { slug: "buru", name: "Buru" },
  { slug: "buru-selatan", name: "Buru Selatan" },
  { slug: "kepulauan-aru", name: "Kepulauan Aru" },
  { slug: "kepulauan-tanimbar", name: "Kepulauan Tanimbar" },
  { slug: "maluku-barat-daya", name: "Maluku Barat Daya" },
  { slug: "maluku-tengah", name: "Maluku Tengah" },
  { slug: "maluku-tenggara", name: "Maluku Tenggara" },
  { slug: "seram-bagian-barat", name: "Seram Bagian Barat" },
  { slug: "seram-bagian-timur", name: "Seram Bagian Timur" },

  // ── MALUKU UTARA ──
  { slug: "ternate", name: "Ternate" },
  { slug: "tidore-kepulauan", name: "Tidore Kepulauan" },
  { slug: "halmahera-barat", name: "Halmahera Barat" },
  { slug: "halmahera-selatan", name: "Halmahera Selatan" },
  { slug: "halmahera-tengah", name: "Halmahera Tengah" },
  { slug: "halmahera-timur", name: "Halmahera Timur" },
  { slug: "halmahera-utara", name: "Halmahera Utara" },
  { slug: "kepulauan-sula", name: "Kepulauan Sula" },
  { slug: "pulau-morotai", name: "Pulau Morotai" },
  { slug: "pulau-taliabu", name: "Pulau Taliabu" },

  // ── PAPUA BARAT DAYA ──
  { slug: "sorong", name: "Sorong" },
  { slug: "sorong-kota", name: "Sorong" },
  { slug: "maybrat", name: "Maybrat" },
  { slug: "raja-ampat", name: "Raja Ampat" },
  { slug: "sorong-selatan", name: "Sorong Selatan" },
  { slug: "tambrauw", name: "Tambrauw" },

  // ── PAPUA BARAT ──
  { slug: "manokwari", name: "Manokwari" },
  { slug: "fakfak", name: "Fakfak" },
  { slug: "kaimana", name: "Kaimana" },
  { slug: "manokwari-selatan", name: "Manokwari Selatan" },
  { slug: "pegunungan-arfak", name: "Pegunungan Arfak" },
  { slug: "teluk-bintuni", name: "Teluk Bintuni" },
  { slug: "teluk-wondama", name: "Teluk Wondama" },

  // ── PAPUA ──
  { slug: "jayapura", name: "Jayapura" },
  { slug: "jayapura-kota", name: "Jayapura" },
  { slug: "biak-numfor", name: "Biak Numfor" },
  { slug: "keerom", name: "Keerom" },
  { slug: "kepulauan-yapen", name: "Kepulauan Yapen" },
  { slug: "mamberamo-raya", name: "Mamberamo Raya" },
  { slug: "sarmi", name: "Sarmi" },
  { slug: "supiori", name: "Supiori" },
  { slug: "waropen", name: "Waropen" },

  // ── PAPUA TENGAH ──
  { slug: "timika", name: "Timika" },
  { slug: "deiyai", name: "Deiyai" },
  { slug: "dogiyai", name: "Dogiyai" },
  { slug: "intan-jaya", name: "Intan Jaya" },
  { slug: "mimika", name: "Mimika" },
  { slug: "nabire", name: "Nabire" },
  { slug: "paniai", name: "Paniai" },
  { slug: "puncak", name: "Puncak" },
  { slug: "puncak-jaya", name: "Puncak Jaya" },

  // ── PAPUA PEGUNUNGAN ──
  { slug: "wamena", name: "Wamena" },
  { slug: "jayawijaya", name: "Jayawijaya" },
  { slug: "lanny-jaya", name: "Lanny Jaya" },
  { slug: "mamberamo-tengah", name: "Mamberamo Tengah" },
  { slug: "nduga", name: "Nduga" },
  { slug: "tolikara", name: "Tolikara" },
  { slug: "yalimo", name: "Yalimo" },
  { slug: "yahukimo", name: "Yahukimo" },

  // ── PAPUA SELATAN ──
  { slug: "merauke", name: "Merauke" },
  { slug: "asmat", name: "Asmat" },
  { slug: "boven-digoel", name: "Boven Digoel" },
  { slug: "mappi", name: "Mappi" },
];

export function getCity(name: string) {
  return cities.find((c) => c.name === name || c.slug === name);
}
